config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'restaurants/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # root "restaurants#index"
  # get 'restaurants' => 'restaurants#index'
  # get 'restaurants/new' => 'restaurants#new'
  # post 'restaurants' => 'restaurants#show'
  # resources :restaurants do
  #   collection do
  #     get :top
  #   end
  # end

  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:index, :new, :create]
  end
  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, acceptance: { accept: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:index, :new, :create]

  def index
    @reviews = Review.where(restaurant_id: @restaurant)
  end

  def new
    # we need @restaurant in our `simple_form_for`
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    >
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, placeholder: "Write the restaurant name here" %>
  <%= f.input :address, placeholder: "Write the restaurant name here" %>
  <%= f.input :category, placeholder: "Write the category here (out of 'chinese', 'italian', japanese, 'french' and 'belgian')" %>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants:</h1>

<ul class="list-group">
<% @restaurants.each do |r| %>
  <li class="list-group-item"><%= link_to r.name, restaurant_path(r) %></li>
<% end %>
</ul>

<%= link_to 'add restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant:</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Address: <%=  @restaurant.address%></p>
<p>Category: <%= @restaurant.category %></p>

<%= link_to 'view Reviews', restaurant_reviews_path(@restaurant) %>
<%= link_to 'add Reviews', new_restaurant_review_path(@restaurant) %>

<br>
<br>

<%# <%= render 'reviews/form' %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, placeholder: "Write your review here" %>
  <%= f.input :rating, placeholder: "Add a rating (1-5)" %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews:</h1>

<ul class="list-group">
<% @reviews.each do |r| %>
  <li class="list-group-item"><%= r.content %> (Rating: <%= r.rating %>)</li>
<% end %>
</ul>


<%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>Add your review below:</h1>
<%= render 'form', restaurant: @restaurant, review: @review %>

<br>
<%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %>